# Generated by Django 5.2.1 on 2025-05-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialCode',
        ),
    ]
