# Generated by Django 5.2.1 on 2025-06-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_photo_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Накопленная награда'),
        ),
    ]
