# Generated by Django 5.2.1 on 2025-05-29 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='projects/avatars/', verbose_name='Аватарка')),
                ('importance', models.CharField(choices=[('low', 'Низкий приоритет'), ('medium', 'Средний приоритет'), ('high', 'Высокий приоритет')], max_length=10, verbose_name='Важность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_workers', models.PositiveIntegerField(verbose_name='Количество работников')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
