# Generated by Django 5.2.1 on 2025-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_projectmessage_task_projectparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
