# Generated by Django 5.2.1 on 2025-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_task_assigned_to_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted_tasks/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('free', 'Свободна'), ('in_progress', 'В процессе'), ('submitted', 'На проверке'), ('done', 'Выполнена')], default='free', max_length=20),
        ),
    ]
