# Generated by Django 5.2.1 on 2025-06-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_personaltask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltask',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='personaltask',
            name='color',
            field=models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зелёный'), ('yellow', 'Жёлтый')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
