# Generated by Django 5.2.1 on 2025-06-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_personaltask_options_remove_personaltask_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltask',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='personaltask',
            name='created_at',
        ),
        migrations.AddField(
            model_name='personaltask',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='status',
            field=models.CharField(choices=[('todo', 'Задачи'), ('in_progress', 'В процессе'), ('done', 'Завершено')], max_length=20),
        ),
    ]
