# Generated by Django 5.2.1 on 2025-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_personaltask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
