# Generated by Django 5.2.1 on 2025-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_task_canceled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparticipant',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
