# Generated by Django 5.2.1 on 2025-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_project_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10),
        ),
    ]
